import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { unzipSync, strFromU8 } from 'fflate'
test('local API is healthy and refuses cross-origin or unapproved writes', async ({ request }) => {
  expect((await request.get('/api/health')).ok()).toBeTruthy()
  expect((await request.post('/api/purchases', { data: {} })).status()).toBe(403)
  expect((await request.get('/api/session', { headers: { Origin: 'https://untrusted.example' } })).status()).toBe(403)
})
test('edit, save, switch formats, and download actual assets', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Make it an occasion.' })).toBeVisible()
  await page.getByLabel('Venue', { exact: true }).fill('The Listening Room, Accra')
  await expect(page.getByTestId('campaign-poster')).toContainText('The Listening Room, Accra')
  await page.reload()
  await expect(page.getByLabel('Venue', { exact: true })).toHaveValue('The Listening Room, Accra')
  await page.getByRole('button', { name: 'Story 9:16' }).click()
  await expect(page.getByTestId('campaign-poster')).toHaveAttribute('viewBox', '0 0 900 1600')
  const pngDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export layout preview', exact: true }).click()
  const png = await pngDownload
  expect(png.suggestedFilename()).toMatch(/layout-preview-story\.png$/)
  const bytes = await readFile((await png.path())!)
  expect(bytes.subarray(1, 4).toString()).toBe('PNG')
  expect(bytes.readUInt32BE(16)).toBe(900); expect(bytes.readUInt32BE(20)).toBe(1600)
  const zipDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download preview pack' }).click()
  const zip = unzipSync(await readFile((await (await zipDownload).path())!))
  expect(Object.keys(zip)).toEqual(expect.arrayContaining(['poster.png', 'story.png', 'caption.txt', 'campaign.json']))
  expect(strFromU8(zip['caption.txt'])).toContain('The Listening Room, Accra')
  expect(strFromU8(zip['READ-ME.txt'])).toContain('LAYOUT PREVIEW')
  expect(errors).toEqual([])
  await png.saveAs('test-results/exported-story.png')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.getByRole('button', { name: 'Poster 3:4' }).click()
  await page.screenshot({ path: 'test-results/studio-desktop.png', fullPage: true })
})
test('wallet guide is accessible and preview mode creates no fake receipts', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Connect wallet', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByText('Set up Binance Wallet in the app', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByRole('button', { name: 'Receipts', exact: true }).click()
  await expect(page.getByText('No purchases yet')).toBeVisible()
})
test('mobile layout remains usable without horizontal scrolling', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await expect(page.getByRole('navigation', { name: 'Campaigns' })).toBeVisible()
  await page.getByRole('button', { name: 'New campaign', exact: true }).last().click()
  await expect(page.getByLabel('Event name', { exact: true })).toHaveValue('UNTITLED GATHERING')
  await expect.poll(async () => (await page.locator('.sidebar').boundingBox())!.x + 245).toBeLessThanOrEqual(0)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: 'test-results/studio-mobile.png', fullPage: true })
})
test('silent motion preview produces a real WebM file', async ({ page }) => {
  await page.goto('/')
  const downloaded = page.waitForEvent('download', { timeout: 30_000 })
  await page.getByRole('button', { name: 'Export silent preview', exact: true }).click()
  const file = await downloaded
  expect(file.suggestedFilename()).toMatch(/silent-preview\.webm$/)
  const bytes = await readFile((await file.path())!)
  expect(bytes.subarray(0, 4).toString('hex')).toBe('1a45dfa3')
  expect(bytes.byteLength).toBeGreaterThan(10000)
})
